//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from m1.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="m1Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface Im1Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="m1Parser.translation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTranslation_unit([NotNull] m1Parser.Translation_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="m1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] m1Parser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="m1Parser.addition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddition([NotNull] m1Parser.AdditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="m1Parser.subtraction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubtraction([NotNull] m1Parser.SubtractionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="m1Parser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] m1Parser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="m1Parser.product"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProduct([NotNull] m1Parser.ProductContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="m1Parser.quotient"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuotient([NotNull] m1Parser.QuotientContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="m1Parser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] m1Parser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="m1Parser.postfix_unary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfix_unary_expression([NotNull] m1Parser.Postfix_unary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="m1Parser.exponentiation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExponentiation([NotNull] m1Parser.ExponentiationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="m1Parser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] m1Parser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="m1Parser.parenthesized"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesized([NotNull] m1Parser.ParenthesizedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="m1Parser.prefix_unary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefix_unary_expression([NotNull] m1Parser.Prefix_unary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="m1Parser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] m1Parser.FunctionContext context);
}
